# Generated by Django 3.0.8 on 2020-07-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_learning_words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api_learning_words.Theme'),
        ),
    ]
