# Generated by Django 3.0.8 on 2020-08-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_learning_words', '0002_auto_20200729_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.TextField(unique=True),
        ),
    ]
