# Generated by Django 3.0.8 on 2020-08-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_learning_words', '0003_auto_20200804_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.TextField(),
        ),
    ]
