# Generated by Django 3.0.8 on 2020-08-11 20:49

from django.db import migrations, models
import learning_words.api_learning_words.validators


class Migration(migrations.Migration):

    dependencies = [
        ('api_learning_words', '0004_auto_20200804_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='sound',
            field=models.FileField(upload_to='sounds/', validators=[learning_words.api_learning_words.validators.validate_file_extension]),
        ),
    ]
