language: python
python:
  - "3.7"

sudo: required
dist: trusty

services:
- docker

before_install: pip install docker-compose

install:
- docker-compose pull
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml build


script:
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml run -e DJANGO_SETTINGS_MODULE=learning_words.settings.testing --no-deps --rm web pytest -vv

