language: python
python:
  - "3.6"

sudo: required
dist: trusty

services:
- docker

before_install:
  - pip install docker-compose
  - pip install codecov

install:
- docker-compose pull
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml build


script:
- docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.ci.yml run -e DJANGO_SETTINGS_MODULE=learning_words.settings.testing --no-deps --rm web

after_success:
  - codecov

