version: '3.7'

services:
  db:
    image: "postgres:11"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    sysctls:
      - net.ipv4.tcp_keepalive_time=600
      - net.ipv4.tcp_keepalive_intvl=60
      - net.ipv4.tcp_keepalive_probes=3

    env_file:
      - .example.env
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: always
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: gunicorn -w 4 learning_words.wsgi -b 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=learning_words.settings.prod
    env_file:
      - .example.env
    volumes:
      - static_files:/static_files
      - media_files:/media_files
    depends_on:
      - db
    restart: always
  nginx:
    #image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
    - static_files:/static_files
    - media_files:/media_files
    depends_on:
      - web
    ports:
      - 80:80
    restart: always


volumes:
  postgres_data:
  static_files:
  media_files:

