version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/ci/web/Dockerfile
    environment:
       - DJANGO_SETTINGS_MODULE=learning_words.settings.testing
    command: ["pytest",  "--cov",  "--cov-report=xml"]