version: '3.7'

services:
  db:
    image: "postgres:11"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: gunicorn -w 4 learning_words.wsgi -b 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./app:/app
      - static_files:/static_files
      - media:/media
    ports:
      - "${HTTP_PORT:-8000}:8000"
    depends_on:
      - db
  nginx:
    #image: nginx
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
    - static_files:/static_files
    - media:/media
    depends_on:
      - web
    ports:
      - 8080:80



volumes:
  postgres_data:
  static_files:
  media: